{
 "title": "Weather",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Temperature/Humidity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "targets": [
    {
     "alias": "Temperature",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "ObsSt",
     "query": "SELECT mean(\"air_temperature\") * 1.8 + 32 as Fahrenheit FROM \"ObsSt\" WHERE $timeFilter GROUP BY time($__interval) fill(linear)",
     "select": [
      [
       { "params": [ "air_temperature" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "* 1.8 + 32" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "Humidity",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "ObsSt",
     "query": "SELECT mean(\"air_temperature\") * 1.8 + 32 as Fahrenheit FROM \"ObsSt\" WHERE $timeFilter GROUP BY time($__interval) fill(linear)",
     "select": [
      [
       { "params": [ "relative_humidity" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Current",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ObsSt",
     "select": [
      [
       { "params": [ "air_temperature" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "* 1.8 + 32" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Pressure",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "pressurehg" } },
   "targets": [
    {
     "expression": "($A*(    (1-(10.4065/($B+283.5585)))** -5.257   ))*0.02953\n",
     "type": "math"
    },
    {
     "alias": "Station Pressure",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "ObsSt",
     "query": "SELECT mean(\"air_temperature\") * 1.8 + 32 as Fahrenheit FROM \"ObsSt\" WHERE $timeFilter GROUP BY time($__interval) fill(linear)",
     "select": [
      [
       { "params": [ "station_pressure" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "/ 33.864" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Wind",
   "type": "fatcloud-windrose-panel",
   "gridPos": { "h": 16, "w": 5, "x": 12, "y": 8 },
   "targets": [
    {
     "alias": "Direction",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "RapidWind",
     "select": [
      [
       { "params": [ "wind_direction" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Speed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "RapidWind",
     "select": [
      [
       { "params": [ "wind_speed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Wind",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "velocitymph" } },
   "targets": [
    {
     "alias": "Wind Speed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "RapidWind",
     "select": [
      [
       { "params": [ "wind_speed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "* 2.23693629" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "Wind Gust",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "ObsSt",
     "select": [
      [
       { "params": [ "wind_gust" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "* 2.23693629" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "Wind Direction",
     "groupBy": [
      { "params": [ "10m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "RapidWind",
     "select": [
      [
       { "params": [ "wind_direction" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       }
      ]
     ]
    }
   ]
  }
 ]
}